import { DataSource, Language, SketchModule } from './types';

// 3. 抽象展示数据获取的接口，默认使用json常量示例
export const MOCK_DATA_SOURCE: DataSource = {
  totalRevenue: 1258900,
  activeUsers: 45230,
  newSignups: 1205,
  conversionRate: "3.2%",
  monthlySales: [120, 150, 180, 220, 300, 280, 350, 400, 420, 450, 500, 550],
  topRegion: "East China",
  customerSatisfaction: 4.8,
  deviceUsage: [400, 300, 300, 200], // For Pie Chart
  trafficSource: [35, 25, 20, 15, 5] // For Pie Chart
};

// Predefined Component Library
export const COMPONENT_LIBRARY: SketchModule[] = [
  // --- Charts ---
  {
    id: 'lib-bar-chart',
    type: 'chart',
    label: 'Bar Chart',
    description: 'Column chart for comparing categorical data',
    x: 0, y: 0, w: 300, h: 200
  },
  {
    id: 'lib-line-chart',
    type: 'line_chart',
    label: 'Line Chart',
    description: 'Line chart for trends over time',
    x: 0, y: 0, w: 300, h: 200
  },
  {
    id: 'lib-pie-chart',
    type: 'pie_chart',
    label: 'Pie Chart',
    description: 'Pie chart for proportions',
    x: 0, y: 0, w: 250, h: 250
  },
  // --- UI Elements ---
  {
    id: 'lib-stat-card',
    type: 'stat_card',
    label: 'Statistic Card',
    description: 'Highlight a single key metric',
    x: 0, y: 0, w: 200, h: 120
  },
  {
    id: 'lib-button',
    type: 'button',
    label: 'Primary Button',
    description: 'Clickable action button',
    x: 0, y: 0, w: 120, h: 40
  },
  {
    id: 'lib-image',
    type: 'image',
    label: 'Image Placeholder',
    description: 'Placeholder for graphics or photos',
    x: 0, y: 0, w: 100, h: 100
  },
  {
    id: 'lib-text-header',
    type: 'text',
    label: 'Section Header',
    description: 'Large title text',
    x: 0, y: 0, w: 200, h: 50,
    customCode: '<h2 class="text-xl font-bold text-gray-800">Section Title</h2>'
  },
   {
    id: 'lib-table',
    type: 'table',
    label: 'Data Table',
    description: 'Tabular data display',
    x: 0, y: 0, w: 400, h: 200
  }
];

export const UI_TEXT = {
  [Language.ZH]: {
    settings: "设置",
    language: "语言",
    llmModel: "大模型提供商",
    apiKey: "API Key (仅本地存储)",
    apiKeyPlaceholder: "请输入您的 API Key",
    close: "关闭",
    save: "保存",
    sketchTitle: "1. 草图绘制区",
    previewTitle: "2. 组件库",
    canvasTitle: "4. 仪表盘画布",
    propertiesTitle: "3. 组件属性",
    analyze: "AI 识别",
    clear: "清空",
    importImage: "导入图片",
    dataFields: "可用数据字段",
    aiAssistant: "AI 助手",
    typeMessage: "输入消息...",
    analyzing: "正在分析...",
    boundTo: "绑定:",
    noBinding: "未绑定",
    changeProviderWarning: "注意：Gemini 使用环境变量中的 Key，阿里云需在此处输入 Key。",
    chatWelcome: "你好！我是你的 AI 助手。你可以问我关于数据的问题，或者上传图片让我分析。",
    screenshot: "截图",
    screenshotToolTitle: "截图标注",
    toolRect: "矩形",
    toolArrow: "箭头",
    addToMessage: "添加到输入消息",
    closeToolbar: "关闭",
    copy: "复制",
    paste: "粘贴",
    delete: "删除",
    edit: "编辑",
    editModule: "编辑组件",
    label: "标题",
    field: "数据字段",
    canvasHint: "从左侧【组件库】区拖拽组件到此处。",
    previewHint: "绘制草图并点击识别，结果将显示在这里。",
    description: "描述",
    selectComponentHint: "请选择一个组件以编辑属性",
    group: "成组",
    ungroup: "解组",
    multiSelection: "多选",
    multiSelectionHint: "已选中多个组件",
    previewMode: "大屏预览",
    exitPreview: "退出预览",
    codeEditor: "代码编辑",
    viewCode: "查看/编辑代码",
    codePlaceholder: "在此处编写 HTML 代码覆盖默认视图...",
    resetCode: "重置 (使用默认视图)",
    saveCode: "保存代码",
    codeWarning: "注意：使用自定义代码将覆盖默认的图表渲染。",
    // Tools
    toolPen: "钢笔",
    toolLine: "直线",
    toolCircle: "圆形",
    toolSelect: "选择",
    toolText: "文本",
    // Layers
    layer: "图层",
    bringToFront: "置顶",
    sendToBack: "置底",
    bringForward: "上移一层",
    sendBackward: "下移一层",
    // Library Tabs
    tabAI: "AI 识别",
    tabLib: "组件库",
    noAIResults: "暂无识别结果，请先在上方绘制草图并点击“AI 识别”。",
    // Custom Components
    addCustom: "新建组件",
    createCustomTitle: "创建自定义组件",
    componentName: "组件名称",
    htmlContent: "HTML 内容",
    create: "创建",
    cancel: "取消",
    custom: "自定义",
    // Zoom
    zoomIn: "放大",
    zoomOut: "缩小",
    resetView: "重置视图",
  },
  [Language.EN]: {
    settings: "Settings",
    language: "Language",
    llmModel: "LLM Provider",
    apiKey: "API Key (Stored locally)",
    apiKeyPlaceholder: "Enter your API Key",
    close: "Close",
    save: "Save",
    sketchTitle: "1. Sketch Area",
    previewTitle: "2. Component Library",
    canvasTitle: "4. Dashboard Canvas",
    propertiesTitle: "3. Component Properties",
    analyze: "AI Analyze",
    clear: "Clear",
    importImage: "Import Image",
    dataFields: "Available Data Fields",
    aiAssistant: "AI Assistant",
    typeMessage: "Type a message...",
    analyzing: "Analyzing...",
    boundTo: "Bound:",
    noBinding: "None",
    changeProviderWarning: "Note: Gemini uses env var Key, Aliyun requires manual input here.",
    chatWelcome: "Hello! I am your AI assistant. Ask me about the data or upload an image.",
    screenshot: "Screenshot",
    screenshotToolTitle: "Screenshot Tools",
    toolRect: "Rectangle",
    toolArrow: "Arrow",
    addToMessage: "Add to Message",
    closeToolbar: "Close",
    copy: "Copy",
    paste: "Paste",
    delete: "Delete",
    edit: "Edit",
    editModule: "Edit Module",
    label: "Label",
    field: "Data Field",
    canvasHint: "Drag components from the 'Component Library' area to here.",
    previewHint: "Draw a sketch and click Analyze. Results will appear here.",
    description: "Description",
    selectComponentHint: "Select a component to edit properties",
    group: "Group",
    ungroup: "Ungroup",
    multiSelection: "Multi-Selection",
    multiSelectionHint: "Multiple items selected",
    previewMode: "Preview",
    exitPreview: "Exit Preview",
    codeEditor: "Code Editor",
    viewCode: "View/Edit Code",
    codePlaceholder: "Write HTML here to override default view...",
    resetCode: "Reset (Use Default)",
    saveCode: "Save Code",
    codeWarning: "Note: Custom code overrides the default chart rendering.",
    // Tools
    toolPen: "Pen",
    toolLine: "Line",
    toolCircle: "Circle",
    toolSelect: "Select",
    toolText: "Text",
    // Layers
    layer: "Layer",
    bringToFront: "Bring to Front",
    sendToBack: "Send to Back",
    bringForward: "Bring Forward",
    sendBackward: "Send Backward",
    // Library Tabs
    tabAI: "AI Generated",
    tabLib: "Standard Lib",
    noAIResults: "No results yet. Draw a sketch above and click 'AI Analyze'.",
    // Custom Components
    addCustom: "Add Custom",
    createCustomTitle: "Create Custom Component",
    componentName: "Component Name",
    htmlContent: "HTML Content",
    create: "Create",
    cancel: "Cancel",
    custom: "Custom",
    // Zoom
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    resetView: "Reset View",
  }
};